extends SceneTree
func _init() -> void:
	var router := UiCommandRouter.new()
	assert(router.move_item({"id":"blade","x":0,"y":5,"revision":0}).ok)
	assert(router.move_item({"id":"spear","x":5,"y":5,"revision":1}).error == "bounds")
	assert(router.move_item({"id":"potion","x":0,"y":5,"revision":1}).error == "overlap")
	assert(router.move_item({"id":"potion","x":1,"y":0,"revision":0}).error == "stale")
	assert(router.move_item({"id":"potion","x":1.5,"y":0,"revision":1}).error == "integer")
	assert(router.move_item({"id":"potion","x":-1,"y":0,"revision":1}).error == "bounds")
	assert(router.move_item({"id":"potion","x":1,"y":0,"revision":1,"rotation":90}).error == "shape")
	assert(router.revision == 1)
	var bridge := WebUiBridge.new()
	var messages: Array[String] = []
	bridge.outgoing.connect(func(message: String) -> void: messages.append(message))
	bridge.receive(JSON.stringify({"type":"inventory.move_item","payload":{"id":"potion","x":1,"y":0,"revision":0}}))
	assert(bridge.router.revision == 0 and messages.is_empty())
	bridge.receive('{"type":"UI_READY","payload":{}}')
	assert(JSON.parse_string(messages.back()).type == "state.snapshot")
	bridge.receive('{"type":"get_tree().quit","payload":{}}')
	assert(JSON.parse_string(messages.back()).result.error == "command")
	bridge.reset_transport()
	bridge.router.ticks = 5
	bridge.receive('{"type":"UI_READY","payload":{}}')
	assert(JSON.parse_string(messages.back()).payload.ticks == 5)
	bridge.receive("{bad JSON")
	bridge.receive("x".repeat(5000))
	bridge.free()
	print("CEF_ROUTER_OK: bounds/height/overlap/stale/no rotation, bridge whitelist and UI_READY snapshot")
	quit()
