extends Node
var context_notifications: Array[int] = []
class MapFixture extends Node3D:
	var npc_endpoint: NpcInteraction3D
	var characters: Dictionary[int, Node3D] = {}

func _ready() -> void:
	_run.call_deferred()

func _run() -> void:
	var approach := NpcApproach.new()
	approach.start("npc-a")
	approach.set_path(PackedVector3Array([Vector3.ZERO, Vector3(0,0,4), Vector3(5,0,4)]))
	var step: Dictionary = approach.step(Vector3.ZERO, Vector3(5,0,4), 3.0, Vector2.ZERO)
	assert(step.direction == Vector2(0,1) and step.interact == "", "Follow path, not a straight line through obstacles")
	step = approach.step(Vector3(4,0,4), Vector3(5,0,4), 3.0, Vector2.ZERO)
	assert(step.direction == Vector2.ZERO and step.interact == "npc-a", "Stop and request interaction only in range")
	assert(approach.step(Vector3(4,0,4), Vector3(5,0,4), 3.0, Vector2.ZERO).interact == "", "Arrival sends one request")
	approach.start("npc-a")
	step = approach.step(Vector3.ZERO, Vector3(5,0,4), 3.0, Vector2.LEFT)
	assert(step.direction == Vector2.LEFT and approach.target_id == "", "Manual movement cancels arrival")
	approach.start("npc-b")
	assert(approach.path.is_empty(), "New click replaces old route")
	assert(approach.step(Vector3.ZERO, Vector3(5,0,4), 3.0, Vector2.ZERO).direction == Vector2.ZERO, "No path means no movement through obstacles")
	approach.cancel()
	var definition: NpcDefinition = NpcDefinitions.get_definition(&"blacksmith")
	assert(definition != null and definition.validation_errors().is_empty())
	assert(NpcDefinitions.get_definition(&"missing") == null)
	var shop: ShopDefinition = ShopDefinitions.get_definition(&"blacksmith_weapon_shop")
	assert(shop != null and shop.validation_errors().is_empty() and shop.offers.size() == 2)
	assert(ShopDefinitions.get_definition(&"missing") == null)
	assert(definition.get_service(&"weapon_shop").content_ref == shop.shop_id)
	var bad: NpcDefinition = definition.duplicate(true)
	bad.services.append(bad.services[0])
	assert("duplicate_service_id" in bad.validation_errors())
	bad = definition.duplicate(true)
	bad.services[1].content_ref = &"missing"
	assert("unknown_shop" in bad.validation_errors())
	var tied: NpcDefinition = definition.duplicate(true)
	tied.services[0].priority = 20
	tied.services.reverse()
	assert(tied.ordered_services()[0].service_id == &"upgrade", "ID breaks equal-priority ties")
	var bad_shop: ShopDefinition = shop.duplicate(true)
	bad_shop.offers[0].item_definition_id = &"missing"
	bad_shop.offers[0].quantity = 0
	bad_shop.offers[0].price = -1
	for error: String in ["unknown_item", "invalid_quantity", "invalid_price"]:
		assert(error in bad_shop.validation_errors())
	assert(shop.offers[0].price == 1000, "Validation fixtures never mutate loaded definitions")
	assert(NeutralNpc3D.valid_instance_id("map1-blacksmith-01"))
	assert(not NeutralNpc3D.valid_instance_id("../Blacksmith"))
	var map := MapFixture.new()
	add_child(map)
	var endpoint := NpcInteraction3D.new()
	map.add_child(endpoint)
	endpoint.context_changed.connect(context_notifications.append)
	endpoint._publish(7)
	assert(context_notifications.is_empty(), "An unchanged inactive context emits no change")
	var actor := preload("res://source/common/gameplay/npcs/blacksmith_fixture.tscn").instantiate() as NeutralNpc3D
	map.add_child(actor)
	assert(endpoint.register_actor(actor))
	assert(not endpoint.register_actor(actor), "Duplicate instance ID is rejected")
	var second := NeutralNpc3D.new()
	second.instance_id = "spike-blacksmith-02"
	second.definition = definition
	map.add_child(second)
	assert(endpoint.register_actor(second), "Definitions can be shared by independent world instances")
	var player := Node3D.new()
	map.add_child(player)
	map.characters[7] = player
	assert(endpoint.interact_for_peer(999, actor.instance_id).error == "unknown_player")
	assert(endpoint.interact_for_peer(7, "missing").error == "unknown_npc")
	assert(endpoint.interact_for_peer(7, actor.instance_id).error == "out_of_range")
	player.global_position = actor.global_position + Vector3(0,0,2)
	assert(endpoint.interact_for_peer(7, actor.instance_id).ok)
	assert(endpoint.contexts[7].npc_definition_id == &"blacksmith")
	assert(endpoint.resolve_npc_service(7, second.instance_id, &"weapon_shop", NpcServiceDefinition.Kind.SHOP).error == "no_interaction")
	assert(endpoint.resolve_npc_service(7, actor.instance_id, &"missing", NpcServiceDefinition.Kind.SHOP).error == "unknown_service")
	assert(endpoint.resolve_npc_service(7, actor.instance_id, &"weapon_shop", NpcServiceDefinition.Kind.UPGRADE).error == "wrong_service_kind")
	endpoint.contexts[7].npc_definition_id = &"old_definition"
	assert(endpoint.resolve_npc_service(7, actor.instance_id, &"weapon_shop", NpcServiceDefinition.Kind.SHOP).error == "stale_context")
	endpoint.contexts[7].npc_definition_id = &"blacksmith"
	var authorized: Dictionary = endpoint.resolve_npc_service(7, actor.instance_id, &"weapon_shop", NpcServiceDefinition.Kind.SHOP)
	assert(authorized.ok and authorized.content_ref == shop.shop_id and authorized.service == definition.get_service(&"weapon_shop"))
	var snapshot: Dictionary = endpoint.snapshot_for_peer(7)
	assert(snapshot.services[0].id == "upgrade" and snapshot.services[1].id == "weapon_shop")
	endpoint._publish(7)
	endpoint._publish(7)
	player.position += Vector3(0.1,0,0)
	endpoint._physics_process(0.25)
	assert(context_notifications == [7], "Repeated checks and movement within range emit no duplicate change")
	assert(endpoint.select_for_peer(7, actor.instance_id, &"weapon_shop").ok)
	assert(endpoint.snapshot_for_peer(7).selectedServiceId == "weapon_shop")
	endpoint._publish(7)
	endpoint._publish(7)
	assert(context_notifications.size() == 2, "Selecting a service emits one change")
	var upgrade_endpoint := Upgrade3D.new()
	map.set("npc_endpoint",endpoint)
	map.add_child(upgrade_endpoint)
	assert(upgrade_endpoint.authorization(7,actor.instance_id,&"weapon_shop").error == "wrong_service_kind")
	assert(upgrade_endpoint.authorization(7,actor.instance_id,&"upgrade").error == "no_interaction")
	assert(endpoint.select_for_peer(7,actor.instance_id,&"upgrade").ok)
	assert(upgrade_endpoint.authorization(7,actor.instance_id,&"upgrade").recipe == UpgradeDefinitions.BASIC)
	player.position += Vector3(20,0,0)
	assert(upgrade_endpoint.authorization(7,actor.instance_id,&"upgrade").error == "out_of_range")
	player.position -= Vector3(20,0,0)
	assert(endpoint.select_for_peer(7,actor.instance_id,&"weapon_shop").ok)
	upgrade_endpoint.free()
	var shop_endpoint := Shop3D.new()
	map.set("npc_endpoint", endpoint)
	map.add_child(shop_endpoint)
	assert(shop_endpoint.open_for_peer(7,actor.instance_id,&"weapon_shop").ok)
	assert(shop_endpoint.snapshot_for_peer(7).offers[0].price==1000)
	assert(shop_endpoint.snapshot_for_peer(7).offers[0].quantity==1)
	assert(shop_endpoint.buy_for_peer(7,second.instance_id,&"weapon_shop",shop.offers[0].offer_id,-1,1000).error=="no_interaction")
	assert(shop_endpoint.buy_for_peer(7,actor.instance_id,&"upgrade",shop.offers[0].offer_id,-1,1100).error=="wrong_service_kind")
	assert(shop_endpoint.buy_for_peer(7,actor.instance_id,&"weapon_shop",shop.offers[0].offer_id,-1,1101).error=="too_fast")
	assert(endpoint.clear_service_for_peer(7).ok and endpoint.contexts.has(7))
	endpoint._publish(7)
	endpoint._publish(7)
	assert(context_notifications.size() == 3 and shop_endpoint._open.is_empty(), "Clearing a service emits once and closes the Shop")
	assert(not shop_endpoint.snapshot_for_peer(7).active)
	assert(endpoint.select_for_peer(7,actor.instance_id,&"weapon_shop").ok)
	assert(shop_endpoint.open_for_peer(7,actor.instance_id,&"weapon_shop").ok)
	endpoint._publish(7)
	assert(context_notifications.size() == 4)
	actor.disabled_services.append(&"weapon_shop")
	assert(endpoint.resolve_npc_service(7, actor.instance_id, &"weapon_shop", NpcServiceDefinition.Kind.SHOP).error == "service_disabled")
	assert(shop_endpoint.buy_for_peer(7,actor.instance_id,&"weapon_shop",shop.offers[0].offer_id,-1,2000).error=="service_disabled")
	endpoint._physics_process(0.25)
	endpoint._publish(7)
	assert(context_notifications.size() == 5 and shop_endpoint._open.is_empty(), "Disabling the selected service emits once and closes the Shop")
	assert(not shop_endpoint.snapshot_for_peer(7).active)
	assert(endpoint.snapshot_for_peer(7).selectedServiceId == "")
	actor.disabled_services.clear()
	endpoint._publish(7)
	assert(context_notifications.size() == 6, "Re-enabling a service changes its availability")
	assert(endpoint.select_for_peer(7,actor.instance_id,&"weapon_shop").ok)
	assert(shop_endpoint.open_for_peer(7,actor.instance_id,&"weapon_shop").ok)
	endpoint._publish(7)
	assert(context_notifications.size() == 7)
	player.position += Vector3(20,0,0)
	assert(endpoint.resolve_npc_service(7, actor.instance_id, &"weapon_shop", NpcServiceDefinition.Kind.SHOP).error == "out_of_range")
	assert(shop_endpoint.buy_for_peer(7,actor.instance_id,&"weapon_shop",shop.offers[0].offer_id,-1,3000).error=="out_of_range")
	endpoint._physics_process(0.25)
	endpoint._publish(7)
	assert(context_notifications.size() == 8 and shop_endpoint._open.is_empty(), "Leaving range emits one change and closes the Shop")
	assert(not endpoint.snapshot_for_peer(7).active and endpoint.contexts.is_empty())
	player.global_position = actor.global_position
	assert(endpoint.interact_for_peer(7, actor.instance_id).ok)
	var other_map := Node3D.new()
	add_child(other_map)
	player.reparent(other_map)
	assert(endpoint.resolve_npc_service(7, actor.instance_id, &"weapon_shop", NpcServiceDefinition.Kind.SHOP).error == "wrong_world")
	player.reparent(map)
	other_map.free()
	endpoint.close_for_peer(7)
	assert(endpoint.contexts.is_empty())
	assert(endpoint.interact_for_peer(7, actor.instance_id).ok)
	endpoint.remove_peer(7)
	assert(endpoint.contexts.is_empty() and not endpoint._observed.has(7), "Peer teardown clears notification history")
	assert(endpoint.interact_for_peer(7, actor.instance_id).ok)
	map.remove_child(actor)
	assert(endpoint.contexts.is_empty() and not endpoint.actors.has(actor.instance_id), "NPC teardown clears contexts")
	actor.free()
	player.global_position = second.global_position
	assert(endpoint.interact_for_peer(7, second.instance_id).ok)
	map.remove_child(endpoint)
	assert(endpoint.contexts.is_empty() and endpoint.actors.is_empty() and endpoint._observed.is_empty(), "World teardown clears all contexts and notification history")
	endpoint.free()
	map.free()
	print("NPC_FOUNDATION_OK: content, identity, map/range/context/service authority and teardown")
	get_tree().quit()
