import {icon} from './icons.js';
// Presentation only. Committed snapshots own placement; command results never do.
export function mountInventory(root,{moveItem,onClose=()=>{}}){
 root.innerHTML=`<section class="window equipment" aria-label="Equipment"><header><span class="crest">✦</span><h1>Equipment</h1></header><div class="equipment-body"><div class="silhouette" aria-hidden="true"><div class="head"></div><div class="torso"></div><div class="legs"></div></div><div class="equipment-slots"></div></div><footer><span class="character-name">Lynanel</span><span>Level 12 · Warrior</span></footer></section><section class="window backpack" aria-label="Inventory"><header><span class="crest">✦</span><h1>Inventory</h1><button class="close" aria-label="Close inventory">×</button></header><div class="category"><span class="active">Backpack</span><span class="capacity"></span></div><div class="inventory-grid" aria-label="Inventory grid"><div class="placement-preview"></div></div><div class="wallet"><span class="coin">◉</span><strong></strong><span>Yang</span></div><footer><span>Drag to move</span><span>Backpack</span></footer></section><aside class="item-tooltip" hidden></aside><p class="inventory-status" role="status">Select an item to inspect it.</p>`;
 const grid=root.querySelector('.inventory-grid'),preview=root.querySelector('.placement-preview'),tooltip=root.querySelector('.item-tooltip');
 let state=null,drag=null,pending=false,selected=null;
 const cell=()=>parseFloat(getComputedStyle(grid).getPropertyValue('--cell'));
 const allowed=(item,x,y)=>x>=0&&x<state.inventory.columns&&y>=0&&y+item.height<=state.inventory.rows&&!state.inventory.items.some(o=>o.id!==item.id&&o.x===x&&y<o.y+o.height&&y+item.height>o.y);
 function inspect(item){selected=item.id;tooltip.hidden=false;tooltip.replaceChildren();const add=(tag,text,cls)=>{const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;tooltip.append(n);};add('small',item.category??'ITEM','rarity');add('h2',item.name);add('p',item.description??'A useful companion on the road.');if(item.attack)add('p',`Attack ${item.attack}`,'stat');add('p',`Size 1 × ${item.height}`);add('small','Drag to move');root.querySelectorAll('.inventory-item').forEach(n=>n.classList.toggle('selected',n.dataset.id===selected));}
 function render(){drag=null;preview.hidden=true;grid.querySelectorAll('.inventory-item,.cell').forEach(n=>n.remove());grid.style.setProperty('--columns',state.inventory.columns);grid.style.setProperty('--rows',state.inventory.rows);
 for(let y=0;y<state.inventory.rows;y++)for(let x=0;x<state.inventory.columns;x++){const n=document.createElement('div');n.className='cell';n.style.left=`${x*cell()}px`;n.style.top=`${y*cell()}px`;grid.append(n);}
 for(const item of state.inventory.items){const n=document.createElement('button');n.type='button';n.className='inventory-item';n.dataset.id=item.id;n.setAttribute('aria-label',item.name);n.innerHTML=icon(item.icon);if(item.quantity>1){const q=document.createElement('span');q.className='quantity';q.textContent=item.quantity;n.append(q);}n.style.left=`${item.x*cell()+2}px`;n.style.top=`${item.y*cell()+2}px`;n.style.height=`${item.height*cell()-4}px`;n.classList.toggle('selected',selected===item.id);
 n.addEventListener('focus',()=>inspect(item));n.addEventListener('pointerenter',()=>{if(!drag)inspect(item);});n.addEventListener('pointerdown',e=>{if(pending||e.button!==0)return;e.preventDefault();inspect(item);n.setPointerCapture(e.pointerId);drag={item,node:n,x:item.x,y:item.y,offset:Math.floor((e.clientY-n.getBoundingClientRect().top)/cell())};n.classList.add('dragging');});
 n.addEventListener('pointermove',e=>{if(drag?.node!==n)return;const r=grid.getBoundingClientRect();drag.x=Math.floor((e.clientX-r.left)/cell());drag.y=Math.floor((e.clientY-r.top)/cell())-drag.offset;preview.hidden=false;preview.style.left=`${drag.x*cell()}px`;preview.style.top=`${drag.y*cell()}px`;preview.style.height=`${item.height*cell()}px`;preview.classList.toggle('invalid',!allowed(item,drag.x,drag.y));});
 n.addEventListener('pointerup',async()=>{if(drag?.node!==n)return;const command={id:item.id,x:drag.x,y:drag.y,revision:state.inventory.revision};drag=null;preview.hidden=true;n.classList.remove('dragging');pending=true;root.classList.add('pending');try{const result=await moveItem(command);root.querySelector('.inventory-status').textContent=result.ok?'Item moved.':`Placement rejected: ${result.error}.`;}catch{root.querySelector('.inventory-status').textContent='No response. Waiting for authoritative state.';}finally{pending=false;root.classList.remove('pending');}});
 n.addEventListener('pointercancel',()=>render());grid.append(n);}
 root.querySelector('.capacity').textContent=`${state.inventory.items.reduce((n,i)=>n+i.height,0)} / ${state.inventory.columns*state.inventory.rows}`;
 root.querySelector('.wallet strong').textContent=Number(state.wallet.balance).toLocaleString('en-US');
 const slots=root.querySelector('.equipment-slots');slots.replaceChildren();for(const entry of state.equipment.slots){const n=document.createElement('div');n.className=`equip-slot ${entry.slot}`;n.innerHTML=entry.icon?icon(entry.icon):'';n.title=entry.label;slots.append(n);}if(selected){const i=state.inventory.items.find(i=>i.id===selected);if(i)inspect(i);else tooltip.hidden=true;}
 }
 const observer=new ResizeObserver(()=>{if(state&&!drag)render();});observer.observe(grid);
 root.querySelector('.close').onclick=onClose;
 return {setState(snapshot){state=structuredClone(snapshot);render();},dispose(){observer.disconnect();root.replaceChildren();}};
}
